### ISSUE TITLE
Change format of the video downloaded

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#202]
Anything but webm.

**Comment by lkiesow** [comment]
While I'm in favor of using h264 + AAC in an mp4 container if possible, this does not seem very urgent to me. Is there any particular problem with the WebM container? And do you just mean the container or does this comment also touch the involved codecs?

**Comment by Melanie-Koller** [comment]
The webm format is not good for Mac OS users. You can't open the video with a quicktime player. Only with a VLC player.

**Comment by LukasKalbertodt** [comment]
It looks like WEBM is actually the only container format supported by Firefox and Chrome. See [these answers](https://stackoverflow.com/q/41739837/2408867), for example. I also checked those sources again and as far as I can tell, there is still no support for anything but WEBM. This is somewhat disappointing, to be honest. 

It looks like iOS/MacOS has problems with the container and not the codecs, right? Because browsers do support multiple codecs, but that won't help if the container is the problem. 

I only see two solutions/workarounds: 

- Just download the video after the Opencast server processed it (into whatever format). This is already possible but not optimal for the user of Studio.
- Somehow implementing the conversion from WEBM to another container format. This requires a ton of time to research and implement. Unlikely that we will do that anytime soon, if ever.

**Comment by LukasKalbertodt** [comment]
It looks like we don't have a lot of choices in this regard. Chrome and Firefox only support WEBM (and MKV, which is just a superset of WEBM) as container format. See [these answers](https://stackoverflow.com/q/41739837/2408867), for example. Both browsers support VP8 and VP9 as video codec. Chrome also supports H264 and AVC1 as video codec (Firefox doesn't), but I don't think that solves the "Apple problem". (I will check that as soon as I get my hands on an Apple device.)

As already noted, users of Apple devices can download software to play WEBM files. It's just not built in.

My completely personal opinion on this is to ignore the issue as it's just Apple refusing to add support for WEBM and related codecs. WEBM and MKV are [basically the only free (as in Open Source license and not patent-encumbered), widely used container formats](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats). The video codecs used in WEBM are [also freely available](https://en.wikipedia.org/wiki/Comparison_of_video_codecs). We see Apple's refusal to support open standards in a few other areas as well (e.g. Vulkan). I don't see why we should invest any time in "fixing" this. This is clearly Apple's choice.

**Comment by oas777** [comment]
While one could argue whether this is an issue with Apple, we should consider the user experience first and foremost. And that user might be using OS and unable/unwilling to install additional software. So we should provide him with an alternative to WEBM.
However, if the browsers don't support this, we will have to stick with it. And maybe turn it into an argument: Upload your media to Opencast to get additional formats!

**Comment by LukasKalbertodt** [comment]
Turns out I was very wrong. Sorry for the misinformation, I can't explain how this mistake happened.

Safari does record MP4 with H264 and AAC as codecs. We just didn't correctly pass the mime type through various objects. The linked PR #421 fixes this. After it's merged, Safari will record MP4 files that the user can immediately download and watch.

**Comment by oas777** [comment]
Good news. Is Safari on OS X the only browser capable of producing MP4? So all browsers on Windows or Linux and Firefox/Chrome on OS X can only produce WEBM?

**Comment by LukasKalbertodt** [comment]
> Is Safari on OS X the only browser capable of producing MP4?

I am not sure. You can test it for yourself by visiting the following page in different browsers (it's just a little tool I wrote):
https://lukaskalbertodt.github.io/mime-test/

As far as I can see, Firefox, Chrome and Edge do *not* support recording as mp4 -- tested on both, Windows and (except for Edge) Linux. All browsers still need to be tested on MacOS.

> So all browsers on Windows or Linux and Firefox/Chrome on OS X can only produce WEBM?

Chrome also seems to support `video/x-matroska` (MKV), but that's a superset of WEBM.

**Comment by oas777** [comment]
Will test this on OS X.

**Comment by oas777** [comment]
![chrome](https://user-images.githubusercontent.com/1752342/74932565-6aef3f80-53e2-11ea-85e6-1ff9170b5068.jpg)
![safari](https://user-images.githubusercontent.com/1752342/74932567-6b87d600-53e2-11ea-9a69-2f6d4349d36a.jpg)
![firefox](https://user-images.githubusercontent.com/1752342/74932569-6c206c80-53e2-11ea-9669-d7383379010c.jpg)

Nope.

**Comment by LukasKalbertodt** [comment]
What browser(s) did you test this with? Which of the three images is which browser?

**Comment by oas777** [comment]
Cf. PM.
