### ISSUE TITLE
URI Rewriting on Github-Pages

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#265]
Publishing on Github Pages does not allow us to configure the server to rewrite URIs as we could do on our own servers.

There are hacky workarounds: Github Pages allows us to implement a custom 404.html. This can be used to redirect back to index.html with the correct path set.

One of the solutions using this is located on https://github.com/rafrex/spa-github-pages

We will have to implement similiar to this.

**Comment by LukasKalbertodt** [comment]
I've taken a look at this but it seems to be somewhat complicated since our solution needs to work for `studio.opencast.org`, for our test deployments `test.studio.opencast.org/folder/` and potentially other places as well. So we can't simply set the `segmentCount` in the 404 script, but somehow have to be smart about it.

It's certainly possible, but I'm not fully convinced that this is the best solution. Is it best practice to use the URL path for SPAs? Couldn't we just always use the query `p=settings` or something like that? Sure, the URL is not as nice, but how often would users even send URLs to other users? Alternatively, we could also just not put the current "view" into the URL, neither path nor query. Because again, I doubt users will send links pointing to the settings page to other users.

Also remember that people setting this up on their own server would have to deal with URI rewriting. So it would be nice if we could avoid that, right?
