### ISSUE TITLE
Camera view mirrored

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-studio#290]
I don't know if that is wanted, but the camera view is mirrored if i compare to https://whereby.com/opencast.

**Comment by LukasKalbertodt** [comment]
Well spotted! I think whereby is the one mirroring the image. I think a few video conference tools do that. That's because in a non-mirrored image, if the user moves, for example, their hand right from their perspective, then the hand moves left in the video image. That sometimes confuses people. Opening the webcam in VLC shows the same non-mirrored image as Opencast Studio.

With that out of the way, I think it's a valid question whether we also want to mirror the image in Studio. For user-facing cameras it might make sense; for cameras filming something else it might be very bad (as in: very confusing). I'd say this is fairly low priority, but we can still think about it!

**Comment by luniki** [comment]
This is done via CSS. As @LukasKalbertodt said we just have to decide what we want.

**Comment by LukasKalbertodt** [comment]
I thought about this again. While we can easily mirror the video shown in Studio directly, we would still record the original video. That would be way more confusing to the user, I think: having a preview video in Studio that is different from the recording. We can of course draw the video stream to a canvas, mirror it and record that, but that's likely a lot of extra resource overhead. 

So I will close this for now.
