### ISSUE TITLE
Redefine link to Opencast

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-studio#303]
The link to Opencast should 

- havea different symbol (maybe the Opencast logo?) and
- open Opencast in a different tab.

**Comment by LukasKalbertodt** [comment]
This will be part of my menu redesign.

**Comment by lkiesow** [comment]
The icon definitely makes sense but a new tab is not a good idea. Browsers have a number of different and very convenient ways of opening links in a new tab or window. But it is very hard to prevent that from happening the other way around (tell browsers to not open it in a new tab/window). 

This means that, as a user, if you want to switch to Opencast, you have to click the icon, switch back to the previous tab and then close that tab to end up with nearly the sate you want, except that if you decide that you want back later, you cannot go back as all this killed your history.

If instead, a link with a non-enforced target is used, users can still open something in a new tab easily, but if they want to switch, they just click the link and if they want to go back later, they still can since the browser history allows that.

This is certainly something with an ongoing debate but big sites like [Wikipedia](https://en.wikipedia.org/wiki/Opencast_(software)) are doing exactly this (e.g. click the link to opencast.org) and it's much more convenient for users.

**Comment by oas777** [comment]
I didn't know this was an issue. Also, I think we should reconsider this after the redesign. Principally, I think it's rather abrupt how you change from Studio to Opencast which is why I thought a new tab might mitigate that change.
