### ISSUE TITLE
Missing "Cancel" button on /settings

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#373]
There is currently no button to dismiss the settings page.

**Comment by LukasKalbertodt** [comment]
This is by design actually. I checked the settings page of multiple big sites (e.g. Twitter and GitHub) and they do not offer a cancel button either. It is assumed that the user will go back where they want to via the menu. And I think I actually agree. The Cancel button made sense when it was a modal dialog, but I don't personally think we need it anymore.
