### ISSUE TITLE
Warning on missings settings.json

### ISSUE THREAD

**Issue by luniki** [elan-ev/opencast-studio#375]
Currently there is a warning of a missing settings.json even if we are running in standalone mode. As there are currently no consequences to a missing settings file this warning should be muted too.

**Comment by LukasKalbertodt** [comment]
It's not warning because of the `settings.json`, but because the user did not actively set an opencast connection yet. (Of course, with a fully configured `settings.json`, the connection would be configured by default.)

But this warning was only there temporarily since users could not configure the connection after recording. I will remove the warning completely as it's not useful anymore.
