### ISSUE TITLE
Content Exceeds Screen Size

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#399]
In landscape mode, the audio selector will exceed the screen size of mobile devices

![aaaaaaaaaaa_Screenshot_20200205-151417](https://user-images.githubusercontent.com/1008395/73861299-1c1ba480-483d-11ea-9fab-1b4f8ef364b2.jpg)

**Comment by LukasKalbertodt** [comment]
Yes, that is unfortunate. I am aware of this. The problem is that you need some kind of minimum height in any case. It won't all fit in 50px, obviously. To decide for a minimum height is the difficult part. In video-source selection and audio-source selection, fitting everything in the "phone landscape" height is very tricky. Look at your screenshot, for example. How would we shrink this? I mean there are still some possibilities, but nothing particularly easy or nice. At least I couldn't think of a better way. 

So yes, I am unhappy that the screen overflows, but so far I haven't found a better solution for these extremely low-height devices.
