### ISSUE TITLE
No camera choice if there is none

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#410]
It looks like [we could detect if there is a webcam](https://www.webrtc-experiment.com/DetectRTC/) in which case it would be nice to not be asked if I want to use a webcam and get an error if there is none.

**Comment by LukasKalbertodt** [comment]
Sounds good. But I think we should somehow show this information to the user. The same with screen share. We use "some magic way" to detect if camera/screen share is supported and simply hide buttons in that case. From my personal experience with software, I would always prefer some information (like a warning) instead of just hiding unsupported options.

**Comment by lkiesow** [comment]
Sounds reasonable on a desktop. Graying out the option, overlaying it with e.g. “No camera detected” sounds reasonable. On a mobile device, however, you will use up a lot of screen for this and I think it's fine to hide these options consistently on all mobile devices, basically saying that there is no such option on these devices.

**Comment by LukasKalbertodt** [comment]
Fixed by #507
