### ISSUE TITLE
UX: Can't upload when disconnected in the "Review" step

### ISSUE THREAD

**Issue by Rillke** [elan-ev/opencast-studio#559]
Proceeding to the review step will send a request to `me.json`. If that request fails, the user receives the following warning:
![image](https://user-images.githubusercontent.com/2311611/79069874-fb0a8080-7cd1-11ea-9758-1cfc9cdd281a.png)

Clicking _the settings_ link will show no server connection settings if they are fully specified in the settings.json or through URL parameters. There is no "back to recording" link, so users may get additionally confused.

![Screen Shot 2020-04-12 at 15 27 55-fullpage](https://user-images.githubusercontent.com/2311611/79069913-34db8700-7cd2-11ea-9ec9-8545ed1cb21f.png)

As a user I can't see how I can upload the recording to Opencast now. People told me, I can disconnect from the Internet while recording, and sometimes my WiFi disconnects. How can I tell Studio that the connection has been re-established now?

----
Version: f55179b

**Comment by LukasKalbertodt** [comment]
This should be fixed now. The fix is deployed [here](https://test.studio.opencast.org/build-20200511133355-LukasKalbertodt-opencast-studio-000222-upload-warnings/), will be deployed on `studio.opencast.org` in a few days and will be included in the Opencast 8.4 release. If you think this problem is not fixed, let us know!
