### ISSUE TITLE
Usage of ☒ in dialogs

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-studio#90]
In Opencast Studio, some dialog boxes have a ☒-button to dismiss the dialog others don't. I'm personally in favor of proper action buttons which may also contain “dismiss” but we should at least be consistent. We even have cases where we already have this, making the ☒-button just superfluous:

<img src="https://user-images.githubusercontent.com/1008395/66787702-f01e9100-eee4-11e9-80ff-1ae23bb3d1ff.jpg" width="300"/>

**Comment by luniki** [comment]
The upload configuration screen does not have the "x" because I defined it this way.

When a user visits OC Studio the first time, she has to configure it before everything else. There is nothing to be done without that configuration.

It is certainly a bug that the configuration modal after clicking on the cog symbol does not have a cancel action.

Uncancellable modals won't have a "x" or a "cancel" action. They should state that fact though.

**Comment by luniki** [comment]
Dialogs will be redone as separate pages.

**Comment by luniki** [comment]
I will fix this in #18
